"""
database/repositories/chat_repository.py
──────────────────────────────────────────
All database operations for chat_sessions and chat_history tables.

chat_sessions  — one row per conversation (groups messages)
chat_history   — individual messages within a session

CRUD:
  Sessions:
    - create_session(client_id, session_uuid) → int
    - get_sessions_for_client(client_id)      → list[dict]
    - get_session(session_uuid)               → dict | None
    - update_session_title(session_uuid, title)
    - delete_session(session_uuid)

  Messages:
    - save_message(session_id, role, content, client_id) → int
    - get_messages(session_uuid)                          → list[dict]
    - get_recent_messages(session_uuid, limit)            → list[dict]
    - clear_session_messages(session_uuid)
"""

from __future__ import annotations

from typing import Optional

from database.connection import get_db_connection
from utils.logger import get_logger

logger = get_logger(__name__)


class ChatRepository:
    """Data-access layer for chat sessions and messages."""

    # ── Sessions ──────────────────────────────────────────────────────────────

    def create_session(
        self,
        session_uuid: str,
        client_id: Optional[int] = None,
        title: Optional[str] = None,
    ) -> int:
        """
        Create a new chat session record.

        Args:
            session_uuid: UUID string generated by the app (unique).
            client_id:    Optional FK to clients.id (if client is selected).
            title:        Optional session title (auto-generated if None).

        Returns:
            New session row id.
        """
        with get_db_connection() as conn:
            cursor = conn.execute(
                """
                INSERT INTO chat_sessions (session_uuid, client_id, title)
                VALUES (?, ?, ?)
                """,
                (session_uuid, client_id, title),
            )
            new_id = cursor.lastrowid
        logger.debug("ChatRepository.create_session: uuid=%s id=%d", session_uuid, new_id)
        return new_id

    def get_session(self, session_uuid: str) -> Optional[dict]:
        """Return a session dict by UUID, or None."""
        with get_db_connection() as conn:
            row = conn.execute(
                "SELECT * FROM chat_sessions WHERE session_uuid = ?", (session_uuid,)
            ).fetchone()
        return dict(row) if row else None

    def get_sessions_for_client(
        self,
        client_id: int,
        limit: int = 20,
    ) -> list[dict]:
        """
        Return the most recent chat sessions for a client.

        Args:
            client_id: FK to clients.id.
            limit:     Maximum sessions to return.

        Returns:
            List of session dicts with message_count, most recent first.
        """
        with get_db_connection() as conn:
            rows = conn.execute("""
                SELECT
                    s.id, s.session_uuid, s.client_id, s.title,
                    s.created_at, s.updated_at,
                    COUNT(m.id) AS message_count
                FROM chat_sessions s
                LEFT JOIN chat_history m ON m.session_id = s.session_uuid
                WHERE s.client_id = ?
                GROUP BY s.id
                ORDER BY s.updated_at DESC
                LIMIT ?
            """, (client_id, limit)).fetchall()
        return [dict(r) for r in rows]

    def get_all_sessions(self, limit: int = 50) -> list[dict]:
        """Return all sessions across all clients (admin view)."""
        with get_db_connection() as conn:
            rows = conn.execute("""
                SELECT
                    s.id, s.session_uuid, s.client_id, s.title,
                    s.created_at, s.updated_at,
                    c.name AS client_name,
                    COUNT(m.id) AS message_count
                FROM chat_sessions s
                LEFT JOIN clients c ON c.id = s.client_id
                LEFT JOIN chat_history m ON m.session_id = s.session_uuid
                GROUP BY s.id
                ORDER BY s.updated_at DESC
                LIMIT ?
            """, (limit,)).fetchall()
        return [dict(r) for r in rows]

    def update_session_title(self, session_uuid: str, title: str) -> bool:
        """Update the display title of a session."""
        with get_db_connection() as conn:
            cursor = conn.execute(
                "UPDATE chat_sessions SET title=?, updated_at=datetime('now') WHERE session_uuid=?",
                (title, session_uuid),
            )
        return cursor.rowcount > 0

    def touch_session(self, session_uuid: str) -> None:
        """Update updated_at to mark the session as recently active."""
        with get_db_connection() as conn:
            conn.execute(
                "UPDATE chat_sessions SET updated_at=datetime('now') WHERE session_uuid=?",
                (session_uuid,),
            )

    def delete_session(self, session_uuid: str) -> bool:
        """Delete a session and all its messages."""
        with get_db_connection() as conn:
            # Messages are linked by session_id (not FK), so delete them first
            conn.execute(
                "DELETE FROM chat_history WHERE session_id = ?", (session_uuid,)
            )
            cursor = conn.execute(
                "DELETE FROM chat_sessions WHERE session_uuid = ?", (session_uuid,)
            )
        return cursor.rowcount > 0

    def ensure_session_exists(
        self,
        session_uuid: str,
        client_id: Optional[int] = None,
    ) -> None:
        """
        Create the session row if it does not already exist.

        This is idempotent — safe to call on every page load.
        """
        existing = self.get_session(session_uuid)
        if not existing:
            self.create_session(session_uuid, client_id=client_id)

    # ── Messages ──────────────────────────────────────────────────────────────

    def save_message(
        self,
        session_uuid: str,
        role: str,
        content: str,
        client_id: Optional[int] = None,
    ) -> int:
        """
        Persist a single chat message and touch the parent session.

        Args:
            session_uuid: UUID string of the parent session.
            role:         "user" | "assistant".
            content:      Message text.
            client_id:    Optional FK to clients.id (denormalised for fast queries).

        Returns:
            New message row id.
        """
        with get_db_connection() as conn:
            cursor = conn.execute(
                """
                INSERT INTO chat_history (session_id, role, content, client_id)
                VALUES (?, ?, ?, ?)
                """,
                (session_uuid, role, content, client_id),
            )
            new_id = cursor.lastrowid
            # Also update chat_sessions.updated_at
            conn.execute(
                "UPDATE chat_sessions SET updated_at=datetime('now') WHERE session_uuid=?",
                (session_uuid,),
            )
        return new_id

    def get_messages(self, session_uuid: str) -> list[dict]:
        """
        Return all messages in a session, in chronological order.

        Args:
            session_uuid: UUID of the target session.

        Returns:
            List of message dicts with: id, role, content, created_at.
        """
        with get_db_connection() as conn:
            rows = conn.execute("""
                SELECT id, session_id, role, content, client_id, created_at
                FROM chat_history
                WHERE session_id = ?
                ORDER BY created_at ASC, id ASC
            """, (session_uuid,)).fetchall()
        return [dict(r) for r in rows]

    def get_recent_messages(
        self,
        session_uuid: str,
        limit: int = 20,
    ) -> list[dict]:
        """Return the N most recent messages in a session (for context injection)."""
        with get_db_connection() as conn:
            rows = conn.execute("""
                SELECT id, role, content, created_at
                FROM chat_history
                WHERE session_id = ?
                ORDER BY created_at DESC, id DESC
                LIMIT ?
            """, (session_uuid, limit)).fetchall()
        # Return in chronological order (reversed from the query)
        return [dict(r) for r in reversed(rows)]

    def clear_session_messages(self, session_uuid: str) -> int:
        """Delete all messages in a session. Returns count deleted."""
        with get_db_connection() as conn:
            cursor = conn.execute(
                "DELETE FROM chat_history WHERE session_id = ?", (session_uuid,)
            )
        return cursor.rowcount

    def get_message_count(self, session_uuid: str) -> int:
        """Return the number of messages in a session."""
        with get_db_connection() as conn:
            row = conn.execute(
                "SELECT COUNT(*) FROM chat_history WHERE session_id = ?",
                (session_uuid,),
            ).fetchone()
        return row[0] if row else 0
